entities:
  kadzo.v2023.tasks:
    presentations:
      summary:
        title: Сводка по задаче
        params:
          type: object
          properties:
            id:
              title: Идентификатор задачи
              type: string
          required:
            - id
        type: markdown
        template: ../templates/summary.md
        origin:
          base: kadzo.v2023
          schema: kadzo.v2023.entities.schema
          refs: kadzo.v2023.entities.__refs__
        source: >
          (
            $task_id := $params.id;
            $ctx:= base;
            $append(
              [
                {
                    "title": "Идентификатор",
                    "data": [{"content": $task_id}]
                }
              ],
              $props_to_summary($task_id,
                                $ctx."kadzo.v2023.tasks",
                                schema."kadzo.v2023.tasks".schema.patternProperties.*.properties,
                                $ctx, refs)
            );
          )